---
title: "Exposure-Adjusted Adverse Event Summary"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Exposure-Adjusted Adverse Event Summary}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
resource_files:
   - fig/*.png
   - rtf/*.rtf
   - pdf/*.pdf
---

```{r}
library(metalite)
library(metalite.ae)
```

# Data pretreatment
```{r}
# ADSL
adsl <- r2rtf::r2rtf_adsl
adsl$TRTA <- adsl$TRT01A
adsl$TRTA <- factor(adsl$TRTA,
                    levels = c("Placebo", "Xanomeline Low Dose", "Xanomeline High Dose"),
                    labels = c("Placebo", "Low Dose", "High Dose"))
# ADAE
adae <- r2rtf::r2rtf_adae
adae$TRTA <- factor(adae$TRTA,
                    levels = c("Placebo", "Xanomeline Low Dose", "Xanomeline High Dose"),
                    labels = c("Placebo", "Low Dose", "High Dose"))

# Drug-related AE values
adae$related <- ifelse(
  adae$AEREL == "RELATED",
  "Y",
  ifelse(
    toupper(adae$AEREL) == "NOT RELATED",
    "N",
    tools::toTitleCase(tolower(adae$AEREL))
    )
)

# AE outcome
for (i in seq_along(adae$AEOUT)) {
  adae$outcome <- switch(adae$AEOUT[i],
                         "RECOVERED/RESOLVED" = "Resolved",
                         "RECOVERING/RESOLVING" = "Resolving",
                         "RECOVERED/RESOLVED WITH SEQUELAE" = "Sequelae",
                         "NOT RECOVERED/NOT RESOLVED" = "Not Resolved",
                         tools::toTitleCase(tolower(adae$AEOUT[i]))
                         )
}

# AE action
adae$AEACN <- gsub("", "DOSE NOT CHANGED", adae$AEACN)

for (i in seq_along(adae$AEACN)) {
  adae$action_taken[i] <- switch(adae$AEACN[i],
                                 "DOSE NOT CHANGED" = "None",
                                 "DOSE REDUCED" = "Reduced",
                                 "DRUG INTERRUPTED" = "Interrupted",
                                 "DOSE INCREASED" = "Increased",
                                 "NOT APPLICABLE" = "N/A",
                                 "UNKNOWN" = "Unknown",
                                 "''" = "None",
                                 tools::toTitleCase(tolower(adae$AEACN[i]))
                                 )
}

# AE duration with unit
adae$duration <- paste(
  ifelse(
    is.na(adae$ADURN),
    "",
    as.character(adae$ADURN)
    ),
  tools::toTitleCase(tolower(adae$ADURU)),
  sep = " "
)

for (i in seq_along(adae$duration)) {
  if (is.na(adae$ADURN[i])) {
    adae$duration[i] <- ifelse(
      charmatch(toupper(adae$AEOUT[i]), "RECOVERING/RESOLVING") > 0 |
        charmatch(toupper(adae$AEOUT[i]), "NOT RECOVERED/NOT RESOLVED") > 0,
      "Continuing",
      "Unknown"
      )
  }
}

# Assign label
adae <- metalite::assign_label(adae,
                               var = c("related", "outcome", "duration", "AESEV", "AESER", "AEDECOD", "action_taken"),
                               label = c("Related", "Outcome", "Duration", "Intensity", "Serious", "Adverse Event", "Action Taken")
)
```

# Build a metadata
```{r}
plan <- plan(
    analysis = "ae_exp_adj", population = "apat",
    observation = c("wk12", "wk24"), parameter = "any;rel;ser") 

meta <- meta_adam(
    population = adsl,
    observation = adae
    ) |>
  define_plan(plan = plan) |>
  define_population(
    name = "apat",
    group = "TRTA",
    subset = quote(SAFFL == "Y"),
    var = "TRTDUR"
    ) |>
  define_observation(
    name = "wk12",
    group = "TRTA",
    subset = quote(SAFFL == "Y"),
    label = "Weeks 0 to 12"
  ) |>
  define_observation(
    name = "wk24",
    group = "TRTA",
    subset = quote(AOCC01FL == "Y"), # Just for demo, another flag should be used
    label = "Weeks 0 to 24"
  ) |>
  define_parameter(
    name = "rel",
    subset = quote(AEREL %in% c("POSSIBLE", "PROBABLE"))
  ) |>
  define_analysis(
    name = "ae_exp_adj",
    title = "Exposure-Adjusted Adverse Event Summary"
  ) |>
  meta_build()
```

# Prepare exposure-adjusted AE summary
```{r}
x <- prepare_ae_exp_adj(meta,
                        population = "apat",
                        observation = "wk12",
                        parameter = "any;rel;ser",
                        adj_unit = "month")
```

```{r}
x$n
x$total_exposure
x$parameter
x$adj_rate
```

