---
title: "Formula Explanation for EAER"
author: Bing Liu (Jul 26, 2023)
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Exposure-Adjusted Adverse Event Summary}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
resource_files:
   - fig/*.png
   - rtf/*.rtf
   - pdf/*.pdf
---

```{r,echo=FALSE,warning=FALSE, message=FALSE}
library(metalite)
library(metalite.ae)
library(dplyr)
```
 

This is a supplementary document for the file "Exposure-Adjusted Adverse Event Summary (Updated)".  

- Part 1 provides an explanation for the calculation of the EAER(exposure adjusted event rate) of adverse events. 

- Part 2 briefly summarize the programming steps of this calculation. 

A further explanation of the data manipulation steps in Part 2 will be provided in a separate file.

####  1. EAER Formula Explanation

$(1)$ EAER Formula 

Note: This is based on the new definition in main file 'Exposure-Adjusted Adverse Event Summary (Updated)').

$$
\begin{aligned}
EAER_j (EAER~for~Trt_j)
&=\frac{total~number~of~events~for~Trt_j}{total~person-day~for~Trt_j/(exp~factor)}  \\
&=\frac{total~number~of~events~for~Trt_j * exp~factor}{total~person-day~for~Trt_j}
\end{aligned}
$$
The exposure factor (exp factor) will be adjusted depending on the adjustment unit defined by users. For instance, when the adjustment unit is '100 person-month', EAER will be computed as follows:

$$
\begin{aligned}
EAER_j (100~person-month) 
&=\frac{total~number~of~events~for~Trt_j * exp~factor(=100*30.4367)}{total~person-day~for~Trt_j}  \\
&=\frac{total~number~of~events~for~Trt_j * 3043.67}{total~person-day~for~Trt_j}  
\end{aligned}
$$
$(2)$ EAER for different types of AEs 
 
 Below is the EAER definitions for three types of AEs using three treatment groups as an example (PBO, Low Dose, High Dose).
 
$(a)$ ANY AE adj rate  

$$
EAER_{PBO} (100~person-month) =\frac{total~number~of~AEs~for~PBO * 3043.67}{total~person-day~for~PBO}
$$
$$
EAER_{LD} (100~person-month) =\frac{total~number~of~AEs~for~Low~Dose * 3043.67}{total~person-day~for~Low~Dose}
$$

$$
EAER_{HD} (100~person-month) =\frac{total~number~of~AEs~for~High~Dose * 3043.67}{total~person-day~for~High~Dose}
$$
 

$(b)$ Serious AE adj rate  


$$
EAER_{PBO} (100~person-month) =\frac{total~number~of~SAEs~for~PBO * 3043.67}{total~person-day~for~PBO}
$$
$$
EAER_{LD} (100~person-month) =\frac{total~number~of~SAEs~for~Low~Dose * 3043.67}{total~person-day~for~Low~Dose}
$$

$$
EAER_{HD} (100~person-month) =\frac{total~number~of~SAEs~for~High~Dose * 3043.67}{total~person-day~for~High~Dose}
$$
 
 
$(c)$  REL AE adj rate  
  

$$
EAER_{PBO} (100~person-month) =\frac{total~number~of~Drug-Related~AEs~for~PBO * 3043.67}{total~person-day~for~PBO}
$$
$$
EAER_{LD} (100~person-month) =\frac{total~number~of~Drug-Related~AEs~for~Low~Dose * 3043.67}{total~person-day~for~Low~Dose}
$$

$$
EAER_{HD} (100~person-month) =\frac{total~number~of~Drug-Related~AEs~for~High~Dose * 3043.67}{total~person-day~for~High~Dose}
$$
 
  
####  2. Programming Steps of EAER

$(1)$ Data pretreatment

At the end of this step, adae is created.(See .Rmd file for codes)

$(2)$ Build a metadata

At the end of this step, 'meta' is created.(See .Rmd file for codes)

$(3)$ Call function prepare_ae_exp_adj() 

This is a function of the following arguments --- meta, population, observation, parameter, and adj_unit. User can call the function as follows.

      x <- prepare_ae_exp_adj(meta,
                        population = "apat",
                        observation = "wk12",
                        parameter = "any;rel;ser",
                        adj_unit = "month")

The output x will be a list of 11 as follows:

     List of 11

     $ meta           :List of 7
     $ population     : chr "apat"
     $ observation    : chr "wk12"
     $ parameter      : chr "any;rel;ser"
     $ n              :'data.frame':	1 obs. of  3 variables:
     $ order          : NULL
     $ group          : chr "TRTA"
     $ reference_group: NULL
     $ total_exposure :'data.frame':	3 obs. of  2 variables:
     $ adj_rate       :List of 3
     $ group_label    : Factor w/ 3 levels "Placebo","Low Dose",..: 1 3 2
     User can run x$adj_rate to obtain the EAER.
  
More detailed explanation on this part will be inroduced in separate document. 
